### PR TITLE
added tab template to calibration,editor,view and connect views

### PR DESCRIPTION
**Pull request by emrysr**
blanked out the tabs until further developments
created model to act on config file
removed module sidebar includes for global sidebar
added js check for empty values in connect.php
added loglevel dropdown js,css and html
added the "snakbar" user notification

`config/loglevel.json` new endpoint created to get&set emonhub loglevel

fix issue #13 

delwedd

### CODE REVIEW

**Comment by emrysr** [comment]
requires update to emoncms before this can be tested.

https://github.com/emoncms/emoncms/pull/1278

**Comment by glynhudson** [comment]
Nice log level adjust works well. However, when checking out this PR the EmonHub restart button stopped working, reverting https://github.com/emoncms/config/issues/14.

**Comment by emrysr** [comment]
@glynhudson - I've corrected the conflicts and tested it on an emonpi. no errors.

**Comment by glynhudson** [comment]
Thanks, it's working well now

**Pull request merged**
